[package]
name = "hs-bindgen"
version = "0.1.0"
edition = "2021"
description = "Handy macro to generate Haskell bindings"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "1.0", features = [ "full", "extra-traits" ] }
