[package]
name = "hs-bindgen"
version = "0.3.3"
edition = "2021"
description = "Handy macro to generate C-FFI bindings from Rust to Haskell"
repository = "https://github.com/yvan-sraka/hs-bindgen"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "1.0", features = [ "full" ] }
toml = "0.5"
